# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a05f156c9c7f6a7976e85999459206b7ee1b9c24137d88d58abb470a0d87df3c3a1e2ab3c23b728f510e89690403ca1eced25f213305e70d49f90952eacdd8dc

test:
  secret_key_base: e9a71e6349979d2ebd54929e645e92163f3eee0af9ccd6dd202ea8b3a43fda059f4225a4d7e25deec1dd1ca956d819f77b1ad67eba942f8a2f8c7065deb2eaaa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
